### ISSUE TITLE
Safety Dance

### ISSUE THREAD

**Issue by Sammaarra** [mlettini/Best-Playlist-Ever#15]
http://www.rdio.com/artist/Men_Without_Hats/album/Studio_Zeta_Dance_80%2C_Vol._6_1/track/Safety_Dance/

**Comment by mlettini** [comment]
I am still torn on this one. It's catchy, though can be annoying, but it is under 3min. Hrmmm, what do you think @bjhess?

**Comment by bjhess** [comment]
It says 4:37 is the length in my Rdio. Is there a shorter version?

I'm kind of down with the chorus, but other stuff like the intro might make me look around at my friends over drinks. "What's going on? Oh, yeah, Safety Dance."

I wouldn't stand in the way of it getting on the list, but ultimately the playlist must be edited to some degree. So I might hold off on this one.

**Comment by Sammaarra** [comment]
Since when is Barry the Playlist King? 

I thought you were supposed to be on my side, Bizzle.

**Comment by bjhess** [comment]
Ss-ah-ff-ee-tt-yy.

**Comment by mlettini** [comment]
Since Barry became my number 1 fan. You gotta step up your cake, Samara.

Anyway, this song might be too kitschy for my tastes, and its longer than I thought. PASS

**Comment by Sammaarra** [comment]
We're offish enemies.
