### ISSUE TITLE
Midnight Oil - Beds Are Burning

### ISSUE THREAD

**Issue by bjhess** [mlettini/Best-Playlist-Ever#19]
Maybe not party music?

http://rd.io/x/QHZdK27yXA/

**Comment by Sammaarra** [comment]
This guy's voice makes me want to die. Hard pass.

**Comment by bjhess** [comment]
@Sammaarra How can you sleep?

**Comment by mlettini** [comment]
I am thoroughly enjoying the collaboration you guys.

**Comment by mlettini** [comment]
Rdio link in the wild!
