### ISSUE TITLE
Robert Palmer - Addicted to Love

### ISSUE THREAD

**Issue by bjhess** [mlettini/Best-Playlist-Ever#26]
http://rd.io/x/QHZdK2nFqg/

**Comment by mlettini** [comment]
I usually can't stand Robert Palmer songs after about 1/2 way thru.

**Comment by bjhess** [comment]
I hated him when I was growing up. I don't anymore. Probably because of this album: https://open.spotify.com/album/73bPiJRwVPkE8dpyCikfFd.
