### ISSUE TITLE
Loverboy - Working for the Weekend

### ISSUE THREAD

**Issue by bjhess** [mlettini/Best-Playlist-Ever#27]
http://rd.io/x/QHZdK24X4A/

**Comment by mlettini** [comment]
Hell yes.

**Comment by bjhess** [comment]
I'M IN!!!!1!1!!

**Comment by mlettini** [comment]
https://github.com/mlettini/Best-Playlist-Ever/commit/b3d07e378533e858d88720723d773f2b761e94ab
