### ISSUE TITLE
Looking Glass – Brandy

### ISSUE THREAD

**Issue by mlettini** [mlettini/Best-Playlist-Ever#36]
@bjhess @Sammaarra

https://www.youtube.com/watch?v=N-tRXewCAmU

**Comment by bjhess** [comment]
I'm pretty sure @Sammaarra will answer correctly.

**Comment by Sammaarra** [comment]
I don't think it fits on the playlist, and I'm still mad at you both for not letting me add Bette Davis Eyes or Need You Tonight.

No is the wrong answer, isn't it?

**Comment by lanej0** [comment]
> not letting me add Bette Davis Eyes or Need You Tonight

Monsters.

**Comment by Sammaarra** [comment]
I knew @lanej0 would be on my side.

**Comment by mlettini** [comment]
Bette Davis Eyes is a snoozefest

![](http://orig06.deviantart.net/849a/f/2011/094/2/d/pokemon_snooze_fest_by_n0tyourstalk3r-d3d8ncr.png)

**Comment by Sammaarra** [comment]
As I have already stated, your face is a snoozefest.

**Comment by Sammaarra** [comment]
WAIT DID I GET SOMETHING RIGHT!??!

**Comment by mlettini** [comment]
Added
