### ISSUE TITLE
Nu Shooz – I Can't Wait

### ISSUE THREAD

**Issue by bjhess** [mlettini/Best-Playlist-Ever#38]
I don't know, people. I'm kind of dancing.

https://www.youtube.com/watch?v=UJ1tBVtYOBc

If this were a video playlist it would be a no-brainer.

**Comment by mlettini** [comment]
Word, the video alone is amazing. It's a good option though!

**Comment by mlettini** [comment]
🤔

**Comment by mlettini** [comment]
@bjhess this has been stuck in my head all day

**Comment by bjhess** [comment]
#sorrynotsorry
