### ISSUE TITLE
J. Geils Band – Centerfold

### ISSUE THREAD

**Issue by mlettini** [mlettini/Best-Playlist-Ever#42]
https://www.youtube.com/watch?v=BqDjMZKf-wg

**Comment by Sammaarra** [comment]
Isn't this song pretty much required on every 80s-ish playlist?

**Comment by mlettini** [comment]
https://github.com/mlettini/Best-Playlist-Ever/commit/b3d07e378533e858d88720723d773f2b761e94ab
