### ISSUE TITLE
Prince – I Wanna Be Your Lover

### ISSUE THREAD

**Issue by mlettini** [mlettini/Best-Playlist-Ever#45]
https://www.youtube.com/watch?v=Rp8WL621uGM

Need two Prince songs https://github.com/mlettini/Best-Playlist-Ever/issues/18

**Comment by bjhess** [comment]
👍

**Comment by mlettini** [comment]
https://github.com/mlettini/Best-Playlist-Ever/commit/b3d07e378533e858d88720723d773f2b761e94ab
