### ISSUE TITLE
Go West – King of Wishful Thinking

### ISSUE THREAD

**Issue by mlettini** [mlettini/Best-Playlist-Ever#9]
https://www.youtube.com/watch?v=r-z94RCld34

**Comment by bjhess** [comment]
This is a pretty solid suggestion. :facepunch:

**Comment by mlettini** [comment]
Added

**Comment by mlettini** [comment]
Cut https://github.com/mlettini/Best-Playlist-Ever/commit/b3d07e378533e858d88720723d773f2b761e94ab

Good song. Didn't vibe though, and no one knew it.
